[package]
name = "vizia_style"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The style components of vizia"
rust-version = "1.60"

[dependencies]
cssparser = "0.29.6"
femtovg = { git = "https://github.com/rhelmot/femtovg", rev = "e1f3f05cc050c0ed69ca702b368bb5d4eb2cabff", default-features = false, features = ["image-loading"] }
selectors = { version = "0.23.0", path = "./selectors" }
morphorm = {git = "https://github.com/vizia/morphorm", features = ["rounding"], rev = "3d74358fe976249738f58724854270aa2f0fdb4a" }
smallvec = "1.0"
bitflags = "*"