[package]
name = "vizia_style"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "The style components of vizia"
rust-version = "1.60"

[dependencies]
cssparser = "0.29.6"
femtovg = "0.6.0"
selectors = { version = "0.23.0", path = "./selectors" }
# morphorm = {path = "../../../morphorm" }
morphorm = {git = "https://github.com/vizia/morphorm", rev = "a4b6ddee4537d52e4890947195b62f29df8fcc2f" }
smallvec = "1.0"
bitflags = "*"