[package]
name = "vizia"
version = "0.1.0"
edition = "2018"
licence = "MIT"
description = "A Rust GUI Framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
