[package]
name = "vizia"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust GUI Framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "button"
path = "examples/controls/button.rs"

[dependencies]
vizia_derive = {version = "0.1.0", path = "derive"}
femtovg = "0.2.5"
morphorm = {git = "https://github.com/geom3trik/morphorm", features = ["rounding"]}
glutin = "0.27.0"
bitflags = "1.3.2"
keyboard-types = "0.6.1"