[package]
name = "vizia_core"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "Core components of vizia"
rust-version = "1.60"

[features]
clipboard = ["copypasta"]
localization = ["dep:fluent-bundle", "dep:fluent-langneg", "dep:fluent-syntax", "dep:unic-langid", "dep:sys-locale"]
x11 = ["copypasta?/x11"]
wayland = ["copypasta?/wayland"]

[dependencies]
vizia_derive = { path = "../vizia_derive" }
vizia_storage = { path = "../vizia_storage" }
vizia_id = { path = "../vizia_id" }
vizia_input = { path = "../vizia_input" }
vizia_window = { path = "../vizia_window" }

femtovg = { git = "https://github.com/femtovg/femtovg", rev = "87fe627794f3f793d8e3a338c838a2f8e8a8aa9d", default-features = false, features = ["image-loading"] }
image = { version = "0.24.0", default-features = false, features = ["png"] } # inherited from femtovg
morphorm = {git = "https://github.com/vizia/morphorm", features = ["rounding"], rev = "c14e888b1d66719fc3f13ccdb1ea01a10368ef9e" }
bitflags = "1.3.2"
fnv = "1.0.7"
fluent-bundle = {version = "0.15.2", optional = true}
fluent-langneg = {version = "0.13", optional = true}
fluent-syntax = {version = "0.11.0", optional = true}
unic-langid = {version = "0.9", optional = true, features = ["macros"]}
sys-locale = {version = "0.2.0", optional = true}
cssparser = "0.27.2"
unicode-segmentation = "1.8.0"
unicode-bidi = "0.3.7"
copypasta = {version = "0.7.1", optional = true, default-features = false }
instant = "0.1.12"
serde = { version = "1.0", optional = true, features = ["derive"] }

# Required so that doc tests will compile
[dev-dependencies]
vizia_winit = {version = "0.1.0", path = "../vizia_winit" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features = ["console"] }
